<a href="https://colab.research.google.com/github/Syeda-Eman/InnoQuest_C1/blob/main/Data_Science_Cohort_1_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

# Load the data
df = pd.read_csv('Lending-company.csv')

In [23]:
df.head()

,LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,1,LoanID_1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
1,2,LoanID_2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
2,3,LoanID_3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
3,4,LoanID_4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
4,5,LoanID_5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [24]:
# 1. Drop 'LoanID' and 'StringID' columns
df = df.drop(['LoanID', 'StringID'], axis=1)

In [25]:
df.head()

,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
1,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
2,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
3,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
4,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [26]:
# 2. Map Product categories
df['Product'] = df['Product'].map({'Product A': 0, 'Product B': 1, 'Product C': 2, 'Product D': 2, 'Product E': 2, 'Product F': 2})
df.head()

,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,1,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
1,2,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
2,1,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
3,0,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
4,1,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [27]:
# 3. Replace 'NotSpecified' in Gender with mode
# Find the mode of the Gender column
gender_mode = df['CustomerGender'].mode().iloc[0]

# Replace 'NotSpecified' with the mode
df['CustomerGender'] = df['CustomerGender'].replace('NotSpecified', gender_mode)

# Verify the changes
print(df['CustomerGender'].value_counts())
print(f"Mode of Gender column: {gender_mode}")

CustomerGender
Male      710
Female    333
Name: count, dtype: int64
Mode of Gender column: Male

In [28]:
# 4. Extract Location and Region numbers
df['Location'] = df['Location'].str.extract('(\d+)').astype(float)
df['Region'] = df['Region'].str.extract('(\d+)').astype(float)
df.head()

,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,1,Female,3.0,2.0,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
1,2,Female,6.0,6.0,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
2,1,Male,8.0,3.0,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
3,0,Male,26.0,2.0,17600.0,NaN,2200,45,365,3141,4166,16321,Active
4,1,Female,34.0,3.0,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [29]:
# 5. Fill missing values in 'TotalPrice' with mean
df['TotalPrice'] = df['TotalPrice'].fillna(df['TotalPrice'].mean())

In [30]:
df.head()

,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,1,Female,3.0,2.0,17600.000000,04/07/2018,2200,45,365,3221,4166,14621,Active
1,2,Female,6.0,6.0,19562.843811,02/01/2019,2200,45,365,3161,4096,16041,Active
2,1,Male,8.0,3.0,16600.000000,08/12/2016,1000,45,365,2260,3205,16340,NaN
3,0,Male,26.0,2.0,17600.000000,NaN,2200,45,365,3141,4166,16321,Active
4,1,Female,34.0,3.0,21250.000000,28/10/2017,2200,55,365,3570,4745,14720,Active

In [31]:
# 6. Handle date-related operations
df['StartDate'] = pd.to_datetime(df['StartDate'], errors='coerce')
df = df.dropna(subset=['StartDate'])
df['Month'] = df['StartDate'].dt.month
df['Weekday'] = df['StartDate'].dt.dayofweek
df = df.drop('StartDate', axis=1)

<ipython-input-31-5151af6e6444>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['StartDate'].dt.month
<ipython-input-31-5151af6e6444>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Weekday'] = df['StartDate'].dt.dayofweek

In [32]:
df.head()

,Product,CustomerGender,Location,Region,TotalPrice,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus,Month,Weekday
0,1,Female,3.0,2.0,17600.000000,2200,45,365,3221,4166,14621,Active,4,5
1,2,Female,6.0,6.0,19562.843811,2200,45,365,3161,4096,16041,Active,2,4
2,1,Male,8.0,3.0,16600.000000,1000,45,365,2260,3205,16340,NaN,8,4
6,0,Male,25.0,NaN,21250.000000,2200,55,365,1951,3176,18701,Active,4,1
8,0,Male,156.0,6.0,23250.000000,5000,55,365,5850,7375,21250,NaN,3,5

In [33]:
# 7. Examine 'TotalDaysYr' column
print(df['TotalDaysYr'].describe())

count    402.0
mean     365.0
std        0.0
min      365.0
25%      365.0
50%      365.0
75%      365.0
max      365.0
Name: TotalDaysYr, dtype: float64

In [ ]:
#no action needed

In [34]:
# 8. Handle loan status
df = df.dropna(subset=['LoanStatus'])
df = df[df['LoanStatus'] != 'Blocked']
df['LoanStatus'] = df['LoanStatus'].map({'Active': 0, 'Finished Payment': 1})

# Display the first few rows and info of the processed dataframe
print(df.head())
print(df.info())

    Product CustomerGender  Location  Region    TotalPrice  Deposit  \
0         1         Female       3.0     2.0  17600.000000     2200
1         2         Female       6.0     6.0  19562.843811     2200
6         0           Male      25.0     NaN  21250.000000     2200
10        1         Female      13.0     6.0  17600.000000     2200
12        1         Female     579.0     3.0  17600.000000     2200

    DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  AmtPaid360  LoanStatus  \
0          45          365       3221       4166       14621           0
1          45          365       3161       4096       16041           0
6          55          365       1951       3176       18701           0
10         45          365       3260       4405       17380           0
12         45          365       3221       5086       14441           0

    Month  Weekday
0       4        5
1       2        4
6       4        1
10      1        4
12      3        5
<class 'pandas.core.frame.DataFrame'>
Index: 381 entries, 0 to 1035
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product         381 non-null    int64
 1   CustomerGender  381 non-null    object
 2   Location        381 non-null    float64
 3   Region          380 non-null    float64
 4   TotalPrice      381 non-null    float64
 5   Deposit         381 non-null    int64
 6   DailyRate       381 non-null    int64
 7   TotalDaysYr     381 non-null    int64
 8   AmtPaid36       381 non-null    int64
 9   AmtPaid60       381 non-null    int64
 10  AmtPaid360      381 non-null    int64
 11  LoanStatus      381 non-null    int64
 12  Month           381 non-null    int32
 13  Weekday         381 non-null    int32
dtypes: float64(3), int32(2), int64(8), object(1)
memory usage: 41.7+ KB
None